name: mrya
description: Mrya Language is easy use
version: 0.2.0
repository: https://github.com/mrya-lang/Mrya

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  args: ^2.5.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
